#!/usr/bin/env bash

## Install ansible
apt-add-repository -y ppa:ansible/ansible
apt-get update -y
apt-get install -y curl git software-properties-common ansible

## pull ansible
ansible-pull -U https://github.com/rdandnayak/ansible.git
