- hosts: localhost
  connection: local
  vars:
    # source_key: "./.ssh/id_rsa"
    dest_key: "{{ lookup('env', 'HOME') }}/.ssh/id_rsa"
  vars_prompt:
    - name: "user_name"
      prompt: "Enter your full name"
      private: no
      default: "Rohit Dandnayak"

    - name: "user_email"
      prompt: "Enter your email"
      private: no
      default: "rohit.dandnayak@soroco.com"
  pre_tasks:
    - name: Update homebrew
      community.general.homebrew:
        update_homebrew: yes
      tags:
        - macos
    - name: Update Cache
      become: yes
      apt:
        force_apt_get: true
        update_cache: true
        state: present
      tags:
        - node
        - zsh
        - ubuntu
        - install
        - dotfiles
        - stow
  tasks:
    - name: Install core packages
      community.general.homebrew:
        name: ["tmux", "fzf"]
        state: present
      tags:
        - install
        - macos
    - name: Install core packages
      become: yes
      apt:
        name: ["tmux", "stow", "cmake"]
      tags:
        - install
        - ubuntu
    - include: tasks/zsh.yml
    - include: tasks/dotfiles.yml
    - include: tasks/node.yml
    - include: tasks/npm-packages.yml
    # - include: tasks/ssh.yml
    - include: tasks/vim.yml
    - include: tasks/neovim.yml
    - include: tasks/source.yml
