- hosts: localhost
  vars_prompt:
    - name: "user_name"
      prompt: "Enter your full name"
      private: no
      default: "Rohit Dandnayak"

    - name: "user_email"
      prompt: "Enter your email"
      private: no
      default: "rohit.dandnayak@soroco.com"
  pre_tasks:
    - name: Update Cache
      become: true
      apt:
        force_apt_get: true
        update_cache: true
        state: present
      tags:
        - node
        - zsh
        - install
        - dotfiles
        - stow
  tasks:
    - name: Install core packages
      apt:
        name: ["tmux", "stow", "cmake"]
      tags:
        - install
    - include: tasks/zsh.yml
    - include: tasks/vim.yml
    - include: tasks/neovim.yml
    - include: tasks/node.yml
    - include: tasks/npm-packages.yml
    - include: tasks/dotfiles.yml
