- hosts: localhost
  become: true
  pre_tasks:
    - name: Update Cache
      apt:
        update_cache: true
      tags:
        - node
        - zsh
        - install
        - dotfiles
        - stow
  tasks:
    - name: Install core packages
      apt:
        name: ["tmux", "stow", "cmake"]
      tags:
        - install
    - include: tasks/zsh.yml
    - include: tasks/neovim.yml
    - include: tasks/node.yml
    - include: tasks/npm-packages.yml
    - include: tasks/dotfiles.yml
