- name: Check if zshrc exists
  stat:
    path: "~/.zshrc"
  register: zshrc_file_existance
  tags:
    - install
    - dotfiles
    - stow
- name: Removing existing config files
  shell: rm ~/.zshrc
  when: zshrc_file_existance.stat.exists
  tags:
    - install
    - dotfiles
    - stow
- name: Installing stow
  apt: name=stow
  tags:
    - install
    - ubuntu
    - dotfiles
    - stow
- name: Installing stow
  community.general.homebrew:
    name: stow
    state: present
  tags:
    - install
    - macos
    - dotfiles
    - stow
- name: Cloning .dotfiles
  ansible.builtin.git:
    repo: 'https://github.com/rdandnayak/.dotfiles.git'
    dest: "{{ lookup('env', 'HOME') }}/.dotfiles"
    force: yes
    recursive: false
    update: yes
    accept_hostkey: yes
    version: main
  tags:
    - install
    - dotfiles
    - stow

- name: Write Git Config information username
  shell: sed -i -e "s/{ user_name }/{{ user_name }}/g" {{ lookup('env', 'HOME') }}/.dotfiles/git/.gitconfig
  tags:
    - install
    - dotfiles
    - stow

- name: Write Git Config information email
  shell: sed -i -e "s/{ user_email }/{{ user_email }}/g" {{ lookup('env', 'HOME') }}/.dotfiles/git/.gitconfig
  tags:
    - install
    - dotfiles
    - stow

- name: Stow dotfiles
  shell: cd $HOME/.dotfiles && ./ubuntu
  tags:
    - install
    - dotfiles
    - stow
