- name: Remove neovim
  shell: rm -rf ~/neovim
  tags:
    - install
    - neovim
- name: Install neovim dependancy
  shell: apt-get install -y libtool autoconf automake cmake libncurses5-dev g++
  tags:
    - install
    - neovim
- name: Install neovim
  shell: add-apt-repository ppa:neovim-ppa/unstable && apt-get install  -y vim neovim
  tags:
    - install
    - neovim
# - name: Clone Neovim
#   ansible.builtin.git:
#     repo: 'https://github.com/neovim/neovim.git'
#     dest: "{{ lookup('env', 'HOME') }}/neovim"
#   tags:
#     - install
#     - neovim
# - name: Build neovim
#   shell: "cd {{ lookup('env', 'HOME') }}/neovim && make -j 20"
#   tags:
#     - install
#     - neovim
# - name: Install neovim
#   become: true
#   shell: "cd {{ lookup('env', 'HOME') }}/neovim && make install"
#   tags:
#     - install
#     - neovim
- name: Install Vim-Plug
  shell: curl -fLo ~/.local/share/nvim/site/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  tags:
    - install
    - dotfiles
    - neovim
