- name: Install Node
  apt:
    name: ['nodejs', 'npm']
  tags:
    - node
- name: Install n
  npm:
    name: n
    global: true
  tags:
    - node
- name: Install Node 14
  shell: n 14
  tags:
    - node
