
# - name: Install Node
#   become: true
#   apt:
#     name: ['nodejs', 'npm']
#   tags:
#     - node
- name: Install node
  shell: curl -sL https://deb.nodesource.com/setup_14.x | sudo bash -
  tags:
    - node
    - ubuntu

- name: Install node
  shell: sudo apt install -y nodejs
  tags:
    - node
    - ubuntu

- name: Install node
  shell: brew install node@14
  tags:
    - node
    - macos

# - name: Chnage n prefix
#   shell: export N_PREFIX=$HOME/.n

# - name: Install n
#   npm:
#     name: n
#     global: true
#   tags:
#     - node
# - name: Install Node 14
#   shell: n 14
#   tags:
#     - node
