- name: Npm global file exists?
  stat:
    path: $NPM_CONFIG_PREFIX
  register: npm_global_exists
  tags:
    - install
    - node
- name: N global folder
  stat:
    path: $HOME/n
  register: n_global
  tags:
    - install
    - node
# - name: Install Node
#   become: true
#   apt:
#     name: ['nodejs', 'npm']
#   tags:
#     - node
# - name: Install node
#   become: yes
#   shell: curl -sL https://deb.nodesource.com/setup_14.x | bash -
#   tags:
#     - node
#     - ubuntu


# - name: Install node
#   become: yes
#   shell: apt install -y nodejs
#   tags:
#     - node
#     - ubuntu

# - name: Install node
#   shell: brew install node@14
#   tags:
#     - node
#     - macos


- name: Clean WSL path
  shell: echo 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games' >> ~/.zshrc
  when: not n_global.stat.exists
  tags:
    - wsl

- name: Install n
  shell: source ~/.zshrc && curl -L https://git.io/n-install | bash -s -- -y 14.18.2
  when: not n_global.stat.exists
  args:
    executable: /bin/zsh
  tags:
    - install
    - node

# name: Install n
#   shell: n 14.18.2
#   tags:
#     - node

# - name: Source zshrc file
#   shell: source $HOME/.zshrc
#   args:
#     executable: /bin/zsh
#   tags:
#     - install
#     - node
#
- name: Create npm directory ~/.npm-global
  ansible.builtin.file:
    path: $NPM_CONFIG_PREFIX
    state: directory
    mode: '0755'


- include: tasks/source.yml

- name: Set global config prefix
  become: false
  become_user: "{{ lookup('env', 'USER') }}"
  shell: source ~/.zshrc && npm config set prefix $NPM_CONFIG_PREFIX
  args:
    executable: /bin/zsh
  tags:
    - install
    - node

# - name: Chnage n prefix
#   shell: mkdir -p $N_PREFIX
#   when: not n_global_exists.stat.exists
#   tags:
#     - node
