- name: Npm global file exists?
  stat:
    path: $HOME/.npm-global
  register: npm_global_exists
  tags:
    - install
    - node
    - ubuntu
# - name: Install Node
#   become: true
#   apt:
#     name: ['nodejs', 'npm']
#   tags:
#     - node
- name: Install node
  become: yes
  shell: curl -sL https://deb.nodesource.com/setup_14.x | bash -
  tags:
    - node
    - ubuntu


- name: Install node
  become: yes
  shell: apt install -y nodejs
  tags:
    - node
    - ubuntu

- name: Install node
  shell: brew install node@14
  tags:
    - node
    - macos

- name: Create global home directory
  shell: mkdir $HOME/.npm-global
  when: not npm_global_exists.stat.exists
  tags:
    - node
    - ubuntu

- name: Set global config prefix
  shell: npm config set prefix $HOME/.npm-global
  tags:
    - node
    - ubuntu

# - name: Chnage n prefix
#   shell: export N_PREFIX=$HOME/.n

# - name: Install n
#   npm:
#     name: n
#     global: true
#   tags:
#     - node
# - name: Install Node 14
#   shell: n 14
#   tags:
#     - node
