# - name: Npm global file exists?
#   stat:
#     path: $NPM_CONFIG_PREFIX
#   register: npm_global_exists
#   tags:
#     - install
#     - node
- name: N global folder
  stat:
    path: $HOME/.n
  register: n_global
  tags:
    - install
    - node
# - name: Install Node
#   become: true
#   apt:
#     name: ['nodejs', 'npm']
#   tags:
#     - node
# - name: Install node
#   become: yes
#   shell: curl -sL https://deb.nodesource.com/setup_14.x | bash -
#   tags:
#     - node
#     - ubuntu


# - name: Install node
#   become: yes
#   shell: apt install -y nodejs
#   tags:
#     - node
#     - ubuntu

# - name: Install node
#   shell: brew install node@14
#   tags:
#     - node
#     - macos


- name: Install n
  shell: curl -L https://git.io/n-install | bash -s -- -y 14.18.2
  when: not n_global.stat.exists
  tags:
    - node


# - name: Source zshrc file
#   shell: source $HOME/.zshrc
#   args:
#     executable: /bin/bash
#   tags:
#     - zsh

- name: Create global home directory
  shell: mkdir -p $NPM_CONFIG_PREFIX
  tags:
    - node

- name: Set global config prefix
  shell: npm config set prefix $NPM_CONFIG_PREFIX
  tags:
    - node

# - name: Chnage n prefix
#   shell: mkdir -p $N_PREFIX
#   when: not n_global_exists.stat.exists
#   tags:
#     - node
