- name: Install global node packages
  become: false
  become_user: "{{ lookup('env', 'USER') }}"
  shell: source ~/.zshrc && npm i -g typescript eslint typescript-language-server conventional-changelog-cli ts-node npx
  args:
    executable: /bin/zsh
  tags:
    - install
    - node
# - name: Install Yarn
#   npm:
#     name: yarn
#     global: yes
#   tags:
#     - install
#     - node
# - name: Install eslint
#   npm:
#     name: eslint
#     global: yes
#   tags:
#     - install
#     - node
# - name: Install Typescript server
#   npm:
#     name: typescript-language-server
#     global: yes
#   tags:
#     - install
#     - node
#
- name: Install angular cli
  npm:
    name: "@angular/cli"
    global: yes
    ignore_scripts: true
  args:
    executable: $HOME/n/bin
  tags:
    - install
    - node
#       # FIXME: commenting for now since this has some weird error for permissions https://github.com/microsoft/WSL/issues/14
#       # FIXME: similar prblem exists for mac as well
# # - name: Install npx
# #   become: yes
# #   npm:
# #     name: npx
# #     global: yes
# #   tags:
# #     - install
# #     - node

# - name: Conventional Changelog
#   npm:
#     name: conventional-changelog-cli
#     global: yes
#   tags:
#     - install
#     - node
# - name: Install Typescript
#   npm:
#     name: typescript
#     global: yes
#   tags:
#     - install
#     - node
# - name: Install TS-Node
#   npm:
#     name: ts-node
#     global: yes
#   tags:
#     - install
#     - node
