- name: Source zshrc file
  ansible.builtin.shell: source ~/.zshrc
  args:
    executable: /bin/zsh
  tags:
    - zsh
- name: Exec entire shell
  ansible.builtin.shell: exec $SHELL
  args:
    executable: /bin/zsh
  tags:
    - zsh
