- name: Install vim
  shell: sudo add-apt-repository ppa:jonathonf/vim && sudo apt-get install  -y vim
  tags:
    - install
    - vim
    - ubuntu
- name: Install neovim
  community.general.homebrew:
    name: vim
    state: present
  tags:
    - install
    - neovim
