- name: Install curl
  apt: name=curl
  tags:
    - zsh
    - ubuntu
- name: Install git
  apt: name=git
  tags:
    - zsh
    - ubuntu
- name: Install zsh
  become: yes
  apt: name=zsh
  tags:
    - zsh
    - ubuntu
- name: Install curl
  community.general.homebrew:
    name: curl
    state: present
  tags:
    - zsh
    - macos
- name: Install git
  community.general.homebrew:
    name: git
    state: present
  tags:
    - zsh
    - macos
- name: Install zsh
  community.general.homebrew:
    name: zsh
    state: present
  tags:
    - zsh
    - macos
- name: Change shell to zsh
  become: yes
  shell: sudo chsh -s `which zsh`
  tags:
    - zsh
- name: Check if ohMyZsh exists
  stat:
    path: "~/.oh-my-zsh"
  register: oh_my_zsh_exists
  tags:
    - zsh
- name: Install ohmyzsh
  shell: curl -L https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh | sh
  when: not oh_my_zsh_exists.stat.exists
  tags:
    - zsh
- name: Check if ohMyZsh exists
  stat:
    path: "~/.oh-my-zsh/custom/plugins/zsh-autosuggestions"
  register: zsh_auto_suggestion
  tags:
    - zsh
- name: Install zsh plugin for auto suggestions
  ansible.builtin.git:
    repo: "https://github.com/zsh-users/zsh-autosuggestions.git"
    dest: "~/.oh-my-zsh/custom/plugins/zsh-autosuggestions"
  tags:
    - zsh
  when: not zsh_auto_suggestion.stat.exists
- name: Check if ohMyZsh exists
  stat:
    path: "~/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting"
  register: zsh_syntax
  tags:
    - zsh
- name: Install zsh plugin for syntax highlighting
  ansible.builtin.git:
    repo: "https://github.com/zsh-users/zsh-syntax-highlighting.git"
    dest: "~/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting"
  when: not zsh_syntax.stat.exists
  tags:
    - zsh

- name: Path output before zsh
  shell: echo $PATH
  args:
    executable: /bin/zsh
  register: path_output_before_zsh
  tags:
    - zsh
    - ubuntu


- debug:
    var: path_output_before_zsh.stdout_lines

- name: Source zshrc file
  shell: source ~/.zshrc
  args:
    executable: /bin/zsh
  tags:
    - zsh
    - ubuntu

- name: Source zshrc file
  shell: source ~/.zshrc
  args:
    executable: /bin/zsh
  tags:
    - zsh
    - macos

- name: Path Output after zsh
  shell: echo $PATH
  args:
    executable: /bin/zsh
  register: path_output_after_zsh
  tags:
    - zsh
    - ubuntu


- debug:
    var: path_output_after_zsh.stdout_lines
